// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import ActivityFormController from "./activity_form_controller.js"
application.register("activity-form", ActivityFormController)

import AddParticipantController from "./add_participant_controller.js"
application.register("add-participant", AddParticipantController)

import HelloController from "./hello_controller.js"
application.register("hello", HelloController)
